Keep track of balances on all enabled asset types
numus-digital/dola pull request #21
Opened 2021-09-23 10:27 UTC by lrascao

Up until now we were only tracking spot asset balances.

2021-09-24 09:09 UTC, ydm requested changes

2021-09-24 09:09 UTC, ydm commented on holdings.go
> +	ID       string
if id is the key, let's not have it in the map[key]value value struct?

2021-09-24 09:09 UTC, ydm commented on holdings.go
> +	Currency   currency.Code
if the code is the key, let's not have it here?

2021-09-24 09:09 UTC, ydm commented on holdings.go
> +	sync.RWMutex
i prefer having the mutex as a field, not inherited. also, it should be a private field and used only through methods.

2021-09-24 09:09 UTC, ydm commented on holdings.go
> +		return &empty, ErrNeedBalancesStrategy
the idea of returning errors is error handling. since it's impossible to handle the case of a missing balances strategy, it's better to panic and ask the client to (1) either have the balances, or (2) not use related functions/methods

2021-09-24 09:09 UTC, ydm commented on holdings.go
> +	holdings.RLock()
this whole thing from this line to the end of the function should be a dedicated holdings method. also the mutex should not be used outside of hildings.* functions

2021-09-24 09:09 UTC, ydm commented on strategy_balances.go
> +	holdings map[string]*Holdings
can we have a struct instead of pointer?

2021-09-24 09:09 UTC, ydm commented on strategy_balances.go
> +	// nolint: exhaustivestruct
this won't be necessary if rwlock is not inherited

2021-09-24 09:09 UTC, ydm commented on strategy_balances.go
> +	// nolint: exhaustivestruct
also that won't be necessary if rwlock is not inherited

2021-09-24 09:14 UTC, lrascao commented on holdings.go
> +	Currency   currency.Code
i started with that actually, problem is this struct will be used by consumers of the api and it's cumbersome for them to always carry around two parameters: id and struct

2021-09-24 09:14 UTC, lrascao commented on holdings.go
> +	ID       string
same explanation as `CurrencyBalance`

2021-09-24 09:15 UTC, lrascao commented on holdings.go
> +	sync.RWMutex
not inherited really but embedded, it amounts to the same thing at the end. any special reason for the preference?

2021-09-24 09:18 UTC, lrascao commented on holdings.go
> +	holdings.RLock()
since we're exposing a `Holdings` function that returns the whole map and the same map is being updated in `strategy_balances` we need to expose the lock to the consumers of this function. The alternative would be copying the whole map which is resource consuming

2021-09-24 09:19 UTC, lrascao commented on strategy_balances.go
> +	holdings map[string]*Holdings
The pointer is so that the embedded lock doesn't get copied on return

2021-09-24 09:21 UTC, lrascao commented on holdings.go
> +		return &empty, ErrNeedBalancesStrategy
this was left unchanged, but i can change it now

2021-09-24 10:16 UTC, ydm commented on holdings.go
> +	sync.RWMutex
inheritance is used when you want to treat the derived object as a base object here and there. here we don't do that and hence there's no reason to inherit. the golang library also uses field variant, check sync.Map for example.

2021-09-24 10:20 UTC, ydm commented on holdings.go
> +	holdings.RLock()
the holdings structure should provide setters and getters, locked using the rwlock. even this case -- i.e. locking, using, unlocking -- can be handled using a setter

2021-09-24 10:21 UTC, ydm commented on strategy_balances.go
> +	holdings map[string]*Holdings
which return?

2021-09-24 10:22 UTC, ydm commented on strategy_balances.go
> +	holdings map[string]*Holdings
there is a rvo in go, if a struct literal is returned, the lock is not copied.

2021-09-24 10:23 UTC, lrascao commented on holdings.go
> +	sync.RWMutex
the main point here is that we need to expose Lock/Unlock to consumers of this api (since this map is updated concurrently and we don't want to copy it on return), if i have the lock object as a private field i'll then need to expose Lock/Unlock functions that just call out to sync.RWMutex. This is exactly the use-case for golang's composition (which is not inheritance, go doesn't have that).

2021-09-24 10:24 UTC, lrascao commented on holdings.go
> +	holdings.RLock()
yeah, this one is ok, it can be a getter

2021-09-27 09:11 UTC, ydm requested changes

2021-09-27 09:11 UTC, ydm commented on strategy_balances.go
> +		for _, subAccount := range h.Accounts {
setter here?

2021-09-27 09:11 UTC, ydm commented on toolbelt.go
> +	holdings, err := balances.ExchangeHoldings(exchangeName)
it looks a bit blurry -- what is a "holdings" and what is a "balance"

2021-09-27 09:22 UTC, lrascao commented on strategy_balances.go
> +		for _, subAccount := range h.Accounts {
It would be cleaner here, but exposing a setter in the public interface sort of gives the idea to consumers that it's ok to use it. Do you think we should expose it and add comments to it saying: "DO NOT USE"?

2021-09-27 09:24 UTC, lrascao commented on toolbelt.go
> +	holdings, err := balances.ExchangeHoldings(exchangeName)
maybe switch this thing around then? have a `holdings` strategy that keeps track of balances?

2021-09-29 09:45 UTC, lrascao commented on strategy_balances.go
> +		for _, subAccount := range h.Accounts {
ping?

2021-09-29 09:45 UTC, lrascao commented on toolbelt.go
> +	holdings, err := balances.ExchangeHoldings(exchangeName)
ping?

2021-09-30 09:10 UTC, ydm approved these changes

2021-09-30 09:35 UTC, merged