Allow non-websocket enabled exchanges
numus-digital/dola pull request #25
Opened 2021-09-30 09:37 UTC by lrascao

Instead of running an infinite loop of handling websocket messages block forever on a channel.

2021-09-30 10:54 UTC, ydm requested changes

2021-09-30 10:54 UTC, ydm commented on keep.go
> +		// create a channel and just block forever waiting for something
i think it's better to wait on `<-ctx.Done()` and then return

2021-09-30 10:54 UTC, ydm commented on keep.go
> +		// create a channel and just block forever waiting for something
also why not just returning. i don't like leaving a blocked goroutine anyways

2021-09-30 11:03 UTC, lrascao commented on keep.go
> +		// create a channel and just block forever waiting for something
that's what `Stream` currently does when there's no websocket activity

2021-10-01 08:19 UTC, MarkDzulko commented on keep.go
> +		<-ctx.Done()
should this not `return nil `here?

2021-10-01 08:33 UTC, lrascao commented on keep.go
> +		<-ctx.Done()
yeah, i guess it makes sense for symmetry, on both cases it's never reached

2021-10-01 11:22 UTC, MarkDzulko approved these changes

2021-10-01 11:23 UTC, merged